name: thinpic_flutter
description: "A Flutter image compression library using the powerful C language VIPS library"
version: 0.0.5
homepage: http://framira.com/
repository: https://github.com/bhumit822/thinpic_flutter

topics:
  - image_compression
  - compression
  - thinpic
  - thinpic_flutter
  - image
  


environment:
  sdk: ^3.4.0
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.3
  plugin_platform_interface: ^2.0.2
  path_provider: ^2.1.5

dev_dependencies:
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  plugin:
    platforms:
      android:
        ffiPlugin: true
