name: thinpic_flutter
description: Powerfull image compression using libvips
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4
  plugin:
    platforms:
      android:
        package: com.thinpic.thinpic_flutter
        pluginClass: ThinpicFlutterPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0
